---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-operator
spec:
  destination:
    name: osc-cl1
    namespace: acme-operator
  project: os-climate
  source:
    path: acme-operator/overlays/osc/osc-cl1
    repoURL: https://github.com/Gregory-Pereira/ops-argocd.git
    targetRevision: setup-argocd-and-vault
  ignoreDifferences:
    - group: ""
      jsonPointers:
        - /data/cert-issuer.types.acme.openshift.io
      kind: ConfigMap
      name: letsencrypt-live
      namespace: acme-operator
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
  #   - ApplyOutOfSyncOnly=true
