apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kepler
  namespace: openshift-gitops
spec:
  project: os-climate
  source:
    path: kepler/overlays/osc/osc-cl1
    repoURL: https://github.com/Gregory-Pereira/ops-argocd.git
    targetRevision: setup-argocd-and-vault
  destination:
    name: osc-cl1
    namespace: kepler-monitoring
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
