---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfdefs
spec:
  destination:
    name: osc-cl1
    namespace: opendatahub
  project: os-climate
  source:
    path: kfdefs/overlays/osc/osc-cl1
    repoURL: https://github.com/Gregory-Pereira/ops-argocd.git
    targetRevision: setup-argocd-and-vault
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
  #   - ApplyOutOfSyncOnly=true
