apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-app-of-apps-osc-cl1
spec:
  destination:
    namespace: openshift-gitops
    name: osc-cl1
  project: osc-cl1
  source:
    path: argocd/overlays/moc-infra/applications/envs/osc/osc-cl1
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
