apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: openshift-gitops
components:
- ../../../../components/project-admin-rolebindings/osc
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/large
