---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata
spec:
  destination:
    name: osc-cl2
    namespace: openmetadata
  project: os-climate
  source:
    path: openmetadata/overlays/osc/osc-cl2
    repoURL: https://github.com/Gregory-Pereira/ops-argocd.git
    targetRevision: setup-argocd-and-vault
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
  #   - ApplyOutOfSyncOnly=true
